### ISSUE TITLE
Dziel i rządź

### ISSUE THREAD

**Issue by MaciejAZak** [daftcode/daftacademy-python_4beginners-autumn2020#7]
Pytanie do zadania domowego "Dziel i rządź"

Mój kod spełnia wszystkie warunki podane w poleceniu:

Instancję klasy powinno dać się utworzyć na następujące sposoby:
MyFraction(1, 2)
MyFraction(1, denominator=2)
MyFraction(numerator=1, denominator=2)
MyFraction(5) == MyFraction(5, 1)
MyFraction(numerator=6) == MyFraction(numerator=6, denominator=1)
MyFraction(MyFraction(1, 2)) == MyFraction(1, 2)

Dodatkowo mianownik ułamka powinien zawsze być najmniejszą możliwą liczbą.
Przykład:
a = MyFraction(10, 30)
assert 1 == a.numerator
assert 3 == a.denominator

Ułamki powinno dać się do siebie dodać.
MyFraction(5, 4) == MyFraction(2, 4) + MyFraction(3, 4)
Ułamki powinno dać się do siebie porównać.
MyFraction(6, 3) == MyFraction(6, 3)
Dodawanie int też powinno być możliwe.
MyFraction(5, 4) == MyFraction(1, 4) + 1
MyFraction(5, 4) == 1 + MyFraction(1, 4)

Instancje klasy MyFraction powinno dać się rzutować na string
Przykład:
'MyFraction(numerator=1, denominator=2)' == str(MyFraction(1, 2))
'MyFraction(numerator=1, denominator=2)' == repr(MyFraction(1, 2))

Natomiast przy submitowaniu nie są spełnione dwa testy:

**increase_value**
MyFraction must support adding
More info
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 122, in test_increase_value
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=3, denominator=2) is not MyFraction(numerator=1, denominator=1)

**increase_value_by_int**
MyFraction must support adding int
More info
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 84, in test_increase_value_by_int
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=2, denominator=1) is not MyFraction(numerator=1, denominator=1)

Myślę, że powinno być ujęte w poleceniu co należy zrobić by spełnić te warunki, gdyż obecnie nawet nie jestem w stanie powiedzieć czego ode mnie się oczekuje. Na podstawie AssertionErrorów nie da się wywnioskować jaki konkretnie warunek trzeba spełnić. Pozostałe warunki dodawania klasy są spełnione

**add_fraction_to_int
add_int_to_fraction**

**Comment by Latkos** [comment]
Ciekawe pytanie, niestety nie umiem pomóc też bez Twojego kodu, ale mi spełnia increase_value_by_int, więc ten warunek na pewno jest spełnialny. Mi za to nie działa increase_value, z takim info:

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 162, in test_increase_value
    self.assertEqual(result.numerator, expected_num)
AssertionError: 2 != 3

Pewnie jakoś kwestia mojego i Twojego kodu, ale też nie jestem w stanie powiedzieć co w tych asercjach ma się dziać, bo też nie znajduję przypadku, kiedy by kod nie działał.

**Comment by wdebsqi** [comment]
U mnie w **adding** wywala błąd
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 325, in test_adding
    self.assertEqual(result.numerator, expected_num)
AssertionError: 1 != 5
```

Z kolei w **create_composite_keyword_args** i **create_positional_keyword_args**
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 396, in test_creation_composite_positional_args
    self.assertEqual(result.numerator, expected_numerator)
AssertionError: 6 != 3
```
Oczywiście w samym kodzie przy takich assertion błędy nie występują, więc nie mam pojęcia co muszę naprawić.

Edit:
Jeszcze w wielu testach występuje
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 257, in test_increase_value_by_int
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=3, denominator=1) is not MyFraction(numerator=1, denominator=1)
```
Jak wyżej, takie samo assertion w kodzie nie daje błędu.

**Comment by LukasSzymanski** [comment]
Też mam problem z:
**add_fraction_to_int
add_int_to_fraction**
Co ciekawe sprawdziłem, że te same błędy w testach się pojawiają gdy dziedziczymy MyFraction po Fraction z modułu fractions, a to chyba powinno jednak działać prawidłowo

**Comment by the-architect42** [comment]
increase value:

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 152, in test_increase_value
    self.assertEqual(result.numerator, expected_num)
AssertionError: 3 != 1

Trzeba w tym zadaniu przeciążać __iadd__ ? bo zdaje się że tu gdzieś jest coś nie tak ale nie wiem za bardzdo jak to przetestować u siebie tbh normalnie wszystko działa jak sprawdzam sobie sam

właśnie robię pętle co bierze random.randrange() i kręci się dopóki My fraction + My fraction jest inne niż Myfrcation += Myfraction dla tych samych danyc

**Comment by Latkos** [comment]
Szczerze powiem, że udało się zrobić i nie był to błąd assertów, a tylko mojego babola w kodzie ( self.denominator zamiast other.denominator :D ). Więc de facto błędu w assertach nie ma, tylko akurat dawałem takie przypadki, że nie zauważyłem swojego błędu (może Wy też?). 

Jeszcze tak teraz na to wpadłem, że jak macie np. MyFraction(1,3)+MyFraction(2,3) i nie skracacie wyniku, to Wam wyjdzie MyFraction(3,3). A wypadałoby skrócić do MyFraction(1,1)

**Comment by the-architect42** [comment]
No ja też już wiem co było problemem w iadd nie używam konstruktora w którym mam sprowadzenie ułamka do najprostszej postaci :P 
w związku z czym MyFraction(numerator=2, denominator=1) !=
MyFraction(numerator=6, denominator=3)

**Comment by Latkos** [comment]
No czyli to co mówiłem ;) U mnie co innego, no ale faktycznie to w iadd się może wkraść niezauważalnie

**Comment by the-architect42** [comment]
nie jestem pewien czy to poprawne wywołać \__init__() jeszcze raz dla jakiegoś obiektu.. czy może lepiej zrobić "prywatną" metodę biorącą argumenty konstruktora która w konstruktorze będzie wywol i w funkcji \__iadd__? __init\__ () działa w każdym razie w moim przypadku

**Comment by MaciejAZak** [comment]
Hej, a skąd w ogóle informacja że mamy użyć __iadd__ ? w poleceniu przecież nie ma += 

Ponadto ja teraz otrzymuję błąd:

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 131, in test_increase_value
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=1, denominator=1) is not MyFraction(numerator=1, denominator=1)

i niby w jaki sposób MyFraction(numerator=1, denominator=1) is not MyFraction(numerator=1, denominator=1) ????

**Comment by the-architect42** [comment]
Z unit testów jak wypluwa błąd to jest adding test a także increase. Increase to jest powiększ o coś jedną wartość czyli += 
Tak stawiam w każdym razie. Ważne żeby było na zielono wszystko xd

**Comment by admsbk** [comment]
@MaciejAZak mnie też nie przechodzi tylko increase_value_by_int i increase_value, reszta zielono. Zrobiłem add, eq, repr, radd, nie wiem czego tu jeszcze może brakować, żeby przechodziło? Wszystkie przykłady z treści zadania wychodzą.

**increase_value_by_int**
MyFraction must support adding int
More info
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 86, in test_increase_value_by_int
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=2, denominator=1) is not MyFraction(numerator=1, denominator=1)

**increase_value**
MyFraction must support adding
More info
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 124, in test_increase_value
    self.assertIs(result, a)
AssertionError: MyFraction(numerator=3, denominator=2) is not MyFraction(numerator=1, denominator=1)

@the-architect42 z tego co wyczytałem to jeśli nie przeciążysz iadd to używa add, bo to przecież wciąż dodawanie, a sama implementacja iadd ma na celu poprawę wydajności, więc to chyba nie tu problem

**Comment by Latkos** [comment]
@MaciejAZak Wydaje mi się, że jest subtelna różnica między __add__ a __iadd__ przynajmniej wg wykładu i chodzi tu o to, że __iadd__ zwraca self, a __add__ de facto nowy obiekt. Stąd, pozornie bezsensowny, komunikat MyFraction(1,1) is not MyFraction(1,1)-bo to równe pod względem licznika i mianownika obiekty, ale nie te same obiekty w pamięci.

**Comment by admsbk** [comment]
zerknąłem na wykład tak jak napisał @Latkos, dzięki, zrobiłem iadd i teraz nie przechodzi już tylko **increase_value**
MyFraction must support adding
More info
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 134, in test_increase_value
    self.assertEqual(result.numerator, expected_num)
AssertionError: 3 != 1

**Comment by gargass** [comment]
Mi się udało, ale też bym nie przypuszczał, że trzeba użyc iadd

  def __iadd__(self, x):
    a = MyFraction(self)
    b = a + x
    self.numerator = b.numerator
    self.denominator = b.denominator
    return self

**Comment by Latkos** [comment]
@admsbk Mi się wydaje, że to z kolei tutaj może być kwestia, którą poruszyłem wyżej (sprawdź czy w iadd po dodawaniu powiedzmy 2/3+1/3 otrzymujesz 3/3 czy 1/1. Powinno być to drugie :) )

**Comment by admsbk** [comment]
@Latkos to było dokładnie to, dzięki, wszystkie testy zielone :)
